### ISSUE TITLE
无法正常编译

### ISSUE THREAD

**Issue by Lv-zhaoyang** [wyouflf/xPlugin#2]
`AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{}],"original":"AAPT: ../runtime/org.xplugin.demo.module2.id.txt: error: failed reading stable ID file.\n\n    ","tool":"AAPT"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':module2:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: ../runtime/org.xplugin.demo.module2.id.txt: error: failed reading stable ID file.
     
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s`
AS中 Build-Build Apk失败。

另外，Demo中没有插件Apk 手动放到存储目录下，按button后手动安装加载的示列。

**Comment by wyouflf** [comment]
首次编译按照 readme里介绍的这个顺序试试:

清理编译缓存: ./gradlew clean
编译main模块: ./gradlew main:build
编译module1模块: ./gradlew module1:build
编译module2模块: ./gradlew module2:build

**Comment by wyouflf** [comment]
demo的gradle路径写错了, 你点侧边栏的build吧, 这个可以识别相对路径, 我一会儿更新下demo配置

**Comment by Lv-zhaoyang** [comment]
编译成功
